name: Deploy action

on:
  push:
    branches:
      - 'master'


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd deployed/telegram-worker && git checkout master && git pull origin master && exit
            cd deployed && docker stop telegram-worker && docker rm telegram-worker && docker-compose build telegram-worker && docker-compose --env-file ./config/telegram-worker.env up -d telegram-worker && exit
